substitutions:
  device_id: dsmr_ser2net
  device_name: DSMR ser2net
  device_description: "P1 smart meter ser2net proxy"

esphome:
  name: ${device_id}
  comment: "${device_description}"
  name_add_mac_suffix: false
  project:
    name: zuidwijk.slimmelezer
    version: "2.0"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  baud_rate: 115200

api:

ota:

external_components:
  - source: github://tube0013/esphome-stream-server-v2

uart:
  id: uart_dsmr
  baud_rate: 115200
  rx_pin: GPIO5
  rx_buffer_size: 1700

stream_server:
  id: dsmr_stream_server 
  uart_id: uart_dsmr
  port: 3000  

web_server:
  port: 80

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16

sensor:
  - platform: uptime
    name: ${device_name} Uptime

text_sensor:
  - platform: version
    name: ${device_name} ESPHome Version
    hide_timestamp: true

binary_sensor:
  - platform: stream_server
    name: ${device_name} Client Connected
    stream_server: dsmr_stream_server

switch:
  - platform: restart
    name: ${device_name} restart
